### ISSUE TITLE
Streaming CSV from files.

### ISSUE THREAD

**Issue by rossjones** [jimm/csvlixir#1]
As you mention in the TODO part of the readme, it might be useful to be able to stream from a file on disk.  My use-case is >20Mb CSV files and I'm not sure I really want to hold them in memory.

Might http://elixir-lang.org/docs/stable/elixir/File.html#stream!/3 solve this problem? Not sure how utf-8 could be handled whilst reading bytes.

Are there other issues around being able to stream the data?

**Comment by jimm** [comment]
Please see the new v2.0 branch, which supports files and streams.

**Comment by rossjones** [comment]
Fantastic, thank you!

**Comment by jimm** [comment]
Thank YOU. Sorry that it took so long for me to notice your issue on Github. I just added the file/stream behavior this weekend, and have asked the elixir-talk list to comment on my proposed changes. I'd love to get your feedback as well. See https://github.com/jimm/csvlixir/tree/v2.0.
