### ISSUE TITLE
hex package

### ISSUE THREAD

**Issue by williamgueiros** [jimm/csvlixir#3]
i saw in https://hex.pm/packages/csvlixir don't have 2.0.

In other projets, for example elixir the branch master, is the new features, and old version have a branch.

for example, I'm a new developper in the project, i don´t now this diferente using on the branch.

do you like change de master branch to 2.0 ??

**Comment by jimm** [comment]
Ah, I see: experimentation on master with the stable code (v1.0) on a branch. I've done the opposite: the experimentation is on the branch v2.0, and when I feel it is ready I will merge that into master and master will contain the v2.0 code.

**Comment by jimm** [comment]
I think what you suggest makes sense. When the time is right, I'll create a branch off of master and call that v1.0.0. Then I will merge the new code into master, create a v2.0.0 branch for this new code, and publish that to Hex.

**Comment by williamgueiros** [comment]
great idea, that suggestion resolve the problem.
tks

**Comment by williamgueiros** [comment]
do you want help to resolve that ??

**Comment by jimm** [comment]
Thank you for the offer, but no. I'm just waiting to see if any more comments trickle in. I'll probably merge the 2.0 into master and create the new v2.0.0 branch tonight or tomorrow. I'll then push to hex so that CSVLixir 2.0.0 is generally available.

Thanks again for your offer of help.
